version: '3'

services:
  cms:
    container_name: stem-c-cms-prod
    image: registry.heroku.com/stem-c-staging/web
    environment: 
      - DATABASE_HOST=db
    ports:
      - 1337:1337
    depends_on:
      - db
  compile:
    container_name: stem-c-compile-prod
    image: registry.heroku.com/stem-c-compile/web
    restart: always
    ports:
      - 8080:8080
  db:
    container_name: stem-c-db-prod
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      APP_ENVIRONMENT: ${APP_ENVIRONMENT}