name: Create Review App
on: 
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Create review app
        id: app
        uses: STEM-C/auto/review@v0.4.5
        with: 
          base: review
          pipeline: ${{ secrets.PIPELINE_ID }}
          token: ${{ secrets.HEROKU_TOKEN }}
      - name: Import development database
        run: ./scripts/init_db.sh
        env:
          ENVIRONMENT: development
          DATABASE_URL: ${{ steps.app.outputs.database_url }}
          SCRIPT_PATH: ./scripts
      - name: Built, test, and deploy app
        uses: STEM-C/auto/build-test-deploy@v0.6
        with:
          image_name: server
          image_tag: ${{ steps.app.outputs.app_name }}
          app_name: ${{ steps.app.outputs.app_name }}
          app_type: web
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
      - name: Get branch name
        id: get_branch
        run: echo ::set-output name=NAME::${GITHUB_REF#refs/heads/}
      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        if: success()
        id: deployment
        with:
          initial_status: "success"
          token: ${{ github.token }}
          target_url: https://${{ steps.app.outputs.app_name }}.herokuapp.com
          environment: ${{ steps.app.outputs.app_name }}
          ref: ${{ steps.get_branch.outputs.NAME }}