
name: Run Tests
on:
  pull_request:
    branches: [ 'develop', 'master' ]
jobs:
  run-test-suites:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run tests
        uses: STEM-C/CASMM/mocks@v0.7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
